### PR TITLE
Addition of Nasir hussain

### PR DESCRIPTION
**Pull request by nasirhm**
I've added Nasir Hussain and I've let them know that they're on the list here

### CODE REVIEW

**Comment by mashhoodr** [comment]
@nasirhm probably better to do it in the original repo however I will merge this one

**Comment by nasirhm** [comment]
@mashhoodr can you commit your current repo to the original repo

**Comment by mashhoodr** [comment]
@nasirhm you need to create a PR directly to the main repo (and fork from there as well)

**Comment by nasirhm** [comment]
Ah OK @mashhoodr

**Pull request merged**
